sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master

install: true

script:
  - ./gradlew -DTRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER :ccc-service:build :serviceImage:build
  - docker run -d -p 8080:8080 -e CCC_DEBUG=1 --name ccctest sogis/ccc-service
  - ./gradlew :ccc-service:execProbeFromClasses
  - docker logs ccctest
  - docker kill ccctest
  - docker rm ccctest
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sogis/ccc-service:latest
  - docker push sogis/ccc-service:$TRAVIS_BUILD_NUMBER
